### ISSUE TITLE
testing with quick-select script

### ISSUE THREAD

**Issue by Jimmi08** [lonalore/libraries#1]
Hello, 
I tried to use this plugin. Only one problem is that quick-select is now breaking admin area. (it's blinking - repeating loading - no error in console) Frontend works. I tested it with and without your last change of js_manager.php.
![image](https://cloud.githubusercontent.com/assets/5429548/12199687/631275c6-b61a-11e5-8123-02b259a96fe0.png) 

Library test plugin works, so I suppose I have something wrong with e107.behaviors.
My code:
e_libraries.php
```
<?php
class links_page_libraries
{
    function libraries_info()
    {
        $libraries['quick-select'] = array(
            'name' => 'QuickSelect',
           // 'vendor url' => 'http://quick-select.eggbox.io/',
           // 'download url' => 'https://github.com/eggboxio/quick-select',
            'library path' => e_WEB . 'quick-select',
             'version callback' => 'simple_version_callback',
      			'files'        => array(
      				'js'  => array('js/jquery.quickselect.min.js'),
      				'css' => array('css/quickselect.css'),
      			),            
        ); 
        return $libraries;
    }
     function simple_version_callback() {
        // Use some fancy magic to get the version number... or don't.
        return TRUE;
     }
}
```

e_header.php
```
<?php
 
if (!defined('e107_INIT')) { exit; }
 
$variant = null;
$name  = 'quick-select';    
libraries_load($name, $variant);
 
// Plugin settings for javascript.
$settings = array(
  'activeButtonClass' => 'btn-primary active',
  'breakOutAll' => true,
  'buttonClass' => 'btn btn-default',
  'selectDefaultText' => 'Other', // Use constant for multi-language support.
  'wrapperClass' => 'btn-group',
);


e107::js('settings', array('links_page' => $settings));

// Now load behavior.
e107::js('links_page', 'quickselect.init.js');
?>
```

```
var e107 = e107 || {'settings': {}, 'behaviors': {}};

(function ($)
{
    e107.behaviors.initQuickSelect = {
        attach: function (context, settings)
        {
            $(context).find('select').once('quick-select').each(function () {
                $(this).quickselect({
                    activeButtonClass: e107.settings.links_page.activeButtonClass,
                    breakOutValues: e107.settings.links_page.breakOutValues,
                    breakOutAll: e107.settings.links_page.breakOutAll,                   
                    buttonClass: e107.settings.links_page.buttonClass,
                    selectDefaultText: e107.settings.links_page.selectDefaultText,
                    wrapperClass: e107.settings.links_page.wrapperClass
                });
            });
        }
    };

})(jQuery);
```

this should be empty in admin area:
![image](https://cloud.githubusercontent.com/assets/5429548/12199803/35975e58-b61b-11e5-98dc-f4e70ad7ae59.png)

**Comment by lonalore** [comment]
Everything looks good. Can you provide me a link to your plugin?
On the first screenshot appears that the library is loaded, because it replaced the select list. So, you would like to load the quick-select library only on frontend?

**Comment by Jimmi08** [comment]
I will upload it on github, I let you know.  I tested , Library is loaded (working on frontend). In last issue we used e107.behavior to avoid load script in admin area (problem with menu manager). e107.behavior itself worked as should have.  I think that there can be problem because frontend is still legacy, but it's possibility to find what can cause problem.

**Comment by lonalore** [comment]
Behaviors not only run on Frontend, but Admin Areas as well (except menus.php, in iframe).  

So, try something like this:

```php
<?php

if (!defined('e107_INIT')) { exit; }

if(USER_AREA)
{
  $variant = null;
  $name  = 'quick-select';    
  libraries_load($name, $variant);

  // Plugin settings for javascript.
  $settings = array(
    'activeButtonClass' => 'btn-primary active',
    'breakOutAll' => true,
    'buttonClass' => 'btn btn-default',
    'selectDefaultText' => 'Other', // Use constant for multi-language support.
    'wrapperClass' => 'btn-group',
  );

  e107::js('settings', array('links_page' => $settings));

  // Now load behavior.
  e107::js('links_page', 'quickselect.init.js');
}
```

**Comment by Jimmi08** [comment]
That was my misunderstanding, sorry. Your solution works, but I decided to use some selector # instead just select tag (too general). By the way, nice effect on some admin parts:

![image](https://cloud.githubusercontent.com/assets/5429548/12205005/2ceb5350-b638-11e5-8da8-ffc31b4131b9.png)

https://github.com/Jimmi08/links_page

**Comment by lonalore** [comment]
Excellent! :) Looks good ;-)
This library is similar than [Bootstrap Switch](http://www.bootstrap-switch.org/)

**Comment by Jimmi08** [comment]
Done. Plugin updated. I just added test if function_exists('libraries_load'). If you from any reason deactivate libraries plugin  (f.e. by mistake), you got blank page if other plugin uses it. 
Just last question. Is there setting to load js files in footer?

**Comment by lonalore** [comment]
Yes, there is... now. :D Please update your libraries plugin with the latest GitHub files, then change your e_libraries.php:

```php
<?php
class links_page_libraries
{
    function libraries_info()
    {
        $libraries['quick-select'] = array(
            'name' => 'QuickSelect',
           // 'vendor url' => 'http://quick-select.eggbox.io/',
           // 'download url' => 'https://github.com/eggboxio/quick-select',
            'library path' => e_WEB . 'quick-select',
             'version callback' => 'simple_version_callback',
                'files'        => array(
                    'js'  => array('js/jquery.quickselect.min.js' => array(
                      'type' => 'footer', // If not set, the default: 'url'
                      'zone' => 5, // If not set, the default: 2
                    )),
                    'css' => array('css/quickselect.css'),
                ),            
        ); 
        return $libraries;
    }
     function simple_version_callback() {
        // Use some fancy magic to get the version number... or don't.
        return TRUE;
     }
}
```
Then clear cache if necessary.

**Comment by Jimmi08** [comment]
I can't get it to work, But it's not this version, I found that my plugin works just if I have library_test plugin installed. I had to miss something.

**Comment by lonalore** [comment]
Your welcome! :) Thank you for using this plugin! :)
