### ISSUE TITLE
Just question

### ISSUE THREAD

**Issue by Jimmi08** [lonalore/libraries#3]
Is this something that can be use in theme, not just in plugin?

I have theme with maybe 7-8 javascript libraries. Each layout (I can test value of THEME_LAYOUT) use different libraries with different settings. 

Thanks

**Comment by lonalore** [comment]
e_libraries.php addon file can be used now in theme folders too :) Please test it! :)
Update your files to the latest github files, then run update script in your plugin manager.

**Comment by Jimmi08** [comment]
Impossible!  You are amazing. I will test it at the night. Thanks

**Comment by Jimmi08** [comment]
Hi, little mistake in libraries.php (it will create fork if I correct it here)

![image](https://cloud.githubusercontent.com/assets/5429548/12892919/b100ca1c-ce8e-11e5-857d-bfa76a6c8973.png)
- already created plugins work
- admin_config works

![image](https://cloud.githubusercontent.com/assets/5429548/12893028/2708e69a-ce8f-11e5-86a8-435fe943a6c0.png)

Next info later after more testing

**Comment by lonalore** [comment]
Thanks for riporting this. :) Mea culpa... :)

**Comment by Jimmi08** [comment]
You are welcome
